version: '3.8'

services:
  # API 서버
  api-server:
    env_file:
      - ./vue-project/.env.local
    build:
      context: ./vue-project
      dockerfile: Dockerfile.api
    container_name: shinil_project-api-server
    ports:
      - "3001:3001"
    volumes:
      - ./vue-project:/app
      - ./vue-project/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_EXPIRY=86400
      - JWT_REFRESH_EXPIRY=2592000
    networks:
      - shinil-network
    restart: unless-stopped

  # Vue.js 애플리케이션
  vue-app:
    env_file:
      - ./vue-project/.env.local
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    container_name: shinil_project-vue-app
    ports:
      - "3000:3000"
    volumes:
      - ./vue-project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    networks:
      - shinil-network
    depends_on:
      - api-server
    restart: unless-stopped

networks:
  shinil-network:
    driver: bridge 