version: '3.8'

services:
  # API 서버
  api-server:
    build:
      context: ./vue-project
      dockerfile: Dockerfile.api
    container_name: shinil_project-api-server
    ports:
      - "3001:3001"
    volumes:
      - ./vue-project:/app
      - ./vue-project/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - VITE_SUPABASE_URL=https://vbmmfuraxvxlfpewqrsm.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibW1mdXJheHZ4bGZwZXdxcnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzA4ODAsImV4cCI6MjA3MTc0Njg4MH0.Vm_hl7IdeRMNtbm155fk7l_UUbQj6o9_BLV0NTMHbxc
      - JWT_EXPIRY=86400
      - JWT_REFRESH_EXPIRY=2592000
    networks:
      - shinil-network
    restart: unless-stopped

  # Vue.js 애플리케이션
  vue-app:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    container_name: shinil_project-vue-app
    ports:
      - "3000:3000"
    volumes:
      - ./vue-project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - VITE_SUPABASE_URL=https://vbmmfuraxvxlfpewqrsm.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibW1mdXJheHZ4bGZwZXdxcnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzA4ODAsImV4cCI6MjA3MTc0Njg4MH0.Vm_hl7IdeRMNtbm155fk7l_UUbQj6o9_BLV0NTMHbxc
    networks:
      - shinil-network
    depends_on:
      - api-server
    restart: unless-stopped

networks:
  shinil-network:
    driver: bridge 