version: '3.8'

services:
  # Vue.js 프론트엔드 앱
  vue-app:
    build:
      context: ../vue-project
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ../vue-project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=http://localhost:54321
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    networks:
      - shinil-network
    depends_on:
      - supabase-local

  # Express API 서버
  api-server:
    build:
      context: ../vue-project
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=shinil_pms
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - shinil-network
    depends_on:
      - postgres

  # PostgreSQL 데이터베이스 (Supabase용 설정)
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../postgres-init:/docker-entrypoint-initdb.d
    networks:
      - shinil-network
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=5
      -c max_wal_senders=10
      -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Supabase 로컬 개발 환경
  supabase-local:
    image: supabase/supabase-dev
    ports:
      - "54321:54321"  # Supabase Studio
      - "54322:54322"  # API Gateway
      - "54323:54323"  # Database
      - "54324:54324"  # Auth
      - "54325:54325"  # Storage
      - "54326:54326"  # Realtime
      - "54327:54327"  # Edge Functions
    environment:
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
      - DASHBOARD_USERNAME=supabase
      - DASHBOARD_PASSWORD=this_password_is_insecure_and_should_be_updated
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - shinil-network
    depends_on:
      postgres:
        condition: service_healthy

  # pgAdmin (데이터베이스 관리)
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@shinil.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_CSRF_PROTECTION=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - shinil-network
    depends_on:
      - postgres

  # Redis (캐싱용, 선택사항)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shinil-network
    profiles:
      - cache

volumes:
  supabase-data:
  postgres-data:
  pgadmin-data:
  redis-data:

networks:
  shinil-network:
    driver: bridge 